server:
  port: 8080
spring:
  application:
    name: SSO
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: admin123!
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
#
private:
  key:
    path: certificates/private_key.pem
    password: yourpassword
public:
  key:
    path: certificates/public_key.pem
jwt:
  issuer: issub2sds



logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    com.zaxxer.hikari.HikariDataSource: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG

# Swagger configurations
springdoc:
  pathsToMatch: /api/**
  api-docs:
    path: /api/v1/sso-service
  swagger-ui:
    path: /api/v1/sso-service/docs
